version: '2.1'
services:
  postgresql:
    image: postgres:9.4-alpine
    environment:
      - POSTGRES_USER=${POSTGRESQL_USER}
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRES_DB=${POSTGRESQL_DATABASE}
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 30s
      timeout: 10s
      retries: 5

  saloon:
    depends_on:
      postgresql:
          condition: "service_healthy"
    links:
      - postgresql:postgresql.local
    ports:
      - 9000:9000
    build: .
    environment:
      - NODE_ENV=production
      - DEBUG=${DEBUG}
      - HOST=0.0.0.0
      - PORT=9000
      - TOKEN_SECRET=changeme
      - RESET_PASSWORD_TOKEN_SECRET=changeme
      - RESET_PASSWORD_TOKEN_CIPHER=changeme
      - POSTGRESQL_HOST=${POSTGRESQL_HOST}
      - POSTGRESQL_PORT=${POSTGRESQL_PORT}
      - POSTGRESQL_USER=${POSTGRESQL_USER}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
      - TIMEOUT=${TIMEOUT}
